apiVersion: v1
kind: Pod
metadata:
  name: scanner-node
spec:
  containers:
  - name: scanner
    image: whuy/scanner_node:latest
    securityContext:
      privileged: true
      capabilities:
        add:
        - NET_ADMIN
    volumeMounts:
    - name: dev-tun
      mountPath: /dev/net/tun
    command: ["/app/entrypoint.sh"]
  restartPolicy: Never
  volumes:
  - name: dev-tun
    hostPath:
      path: /dev/net/tun
      type: CharDevice