apiVersion: batch/v1
kind: Job
metadata:
  name: {{JOB_NAME}}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{TOOL_NAME}}
          image: {{IMAGE}}
          args: {{ARGS}}        
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2"