apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: scan-system
spec:
  selector:
    app: controller
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP

