apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: scan-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-role
  namespace: scan-system
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-rolebinding
  namespace: scan-system
subjects:
  - kind: ServiceAccount
    name: controller-sa
    namespace: scan-system
roleRef:
  kind: Role
  name: controller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: controller-pv
  labels:
    app: controller
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/controller-db
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-db-pvc
  namespace: scan-system
  labels:
    app: controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: controller
