# manifests/controller-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  name: controller-nodeport
  namespace: scan-system
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000  # External access via Minikube IP:30000
  selector:
    app: controller
