apiVersion: v1
kind: Service
metadata:
  name: scanner-node-api
  namespace: scan-system
spec:
  selector:
    app: scanner-node-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
