apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-node-sa
  namespace: scan-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scanner-node-role
  namespace: scan-system
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scanner-node-rolebinding
  namespace: scan-system
subjects:
  - kind: ServiceAccount
    name: scanner-node-sa
    namespace: scan-system
roleRef:
  kind: Role
  name: scanner-node-role
  apiGroup: rbac.authorization.k8s.io
